#!/bin/sh
# BUILDING FOR LINUX
# TO BUILD FOR LINUX, YOU NEED TO BE USING LINUX. I DON'T KNOW WHY, BUT THAT'S HOW HAXE WORKS.
# MAKE SURE YOU HAVE EVERYTHING INSTALLED BEFORE THIS.
lime build linux -release
