#!/bin/sh
# BUILDING FOR LINUX - DEBUG
# TO BUILD FOR LINUX, YOU NEED TO BE USING LINUX. I DON'T KNOW WHY, BUT THAT'S HOW HAXE WORKS.
# MAKE SURE YOU HAVE EVERYTHING INSTALLED BEFORE THIS.
lime test linux -debug
